name: Build WebAssembly and Deploy to Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest

      - name: Build WebAssembly game
        run: |
          set -euxo pipefail
          mkdir -p dist
          emcc main.cpp -O3 \
            -s USE_SDL=2 \
            -s ALLOW_MEMORY_GROWTH=1 \
            -s WASM=1 \
            --shell-file shell.html \
            -o dist/index.html
          cp sw.js dist/ || true
          cp manifest.webmanifest dist/ || true

      # ✅ New step: use the official Pages deploy action
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
