name: Build WebAssembly and Deploy to Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ✅ Correct Emscripten setup action
      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest

      - name: Build (C++ -> WebAssembly)
        run: |
          mkdir -p dist
          emcc --version
          emcc main.cpp -O3 \
            -s USE_SDL=2 \
            -s ALLOW_MEMORY_GROWTH=1 \
            -s WASM=1 \
            --shell-file shell.html \
            -o dist/index.html
          cp sw.js manifest.webmanifest dist/ || true

      # ✅ Required for Pages deploy
      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
